FROM rocker/r2u:latest

# System helpers often useful in your course
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      git-lfs tree make bash-completion && \
    git lfs install && \
    rm -rf /var/lib/apt/lists/*

# Optional: pin CRAN mirror via Rprofile.site
RUN echo 'options(repos=c(CRAN="https://cloud.r-project.org"))' >> /usr/lib/R/etc/Rprofile.site
